# -*- coding: utf-8 -*-
"""SweezalSuares_547_lab1(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1inUrAtbwrz1LFP923a0n2MxxyFnEUrqN
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (8, 5)
pd.set_option('display.max_columns', None)
# %matplotlib inline

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('CarPrice_Assignment (1).csv')
display(df)

df.shape

df.head()

df.tail()

print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

numcols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
catcols = df.select_dtypes(include=['object']).columns.tolist()
print(f"Numerical attributes ({len(numcols)}): {numcols}")
print(f"Categorical attributes ({len(catcols)}): {catcols}")

print("Missing values per column:")
print(df.isnull().sum())
print(f"\nTotal missing values: {df.isnull().sum().sum()}")
print(f"Duplicate records: {df.duplicated().sum()}")

df.describe()

if df.isnull().sum().sum() > 0:
    for col in numerical_cols:
        df[col] = df[col].fillna(df[col].median())
    for col in categorical_cols:
        df[col] = df[col].fillna(df[col].mode()[0])
    print("Missing values handled.")
else:
    print("No missing values found — nothing to impute.")

df_clean = df.drop(columns=['car_ID'])
df_clean['carbrand'] = df_clean['CarName'].str.split().str[0].str.lower()
df_clean['carbrand'] = df_clean['carbrand'].replace({
    'maxda': 'mazda', 'porcshce': 'porsche', 'toyouta': 'toyota',
    'vokswagen': 'volkswagen', 'vw': 'volkswagen'
})
df_clean = df_clean.drop(columns=['CarName'])

print(f"Unique brands after cleanup: {df_clean['carbrand'].nunique()}")
df_clean['carbrand'].value_counts()

from sklearn.preprocessing import LabelEncoder
df_encoded = df_clean.copy()
binary_cols = ['fueltype', 'aspiration', 'doornumber', 'enginelocation']
le = LabelEncoder()
for col in binary_cols:
    df_encoded[col] = le.fit_transform(df_encoded[col])
cylinder_map = {'two': 2, 'three': 3, 'four': 4, 'five': 5,
                 'six': 6, 'eight': 8, 'twelve': 12}
df_encoded['cylindernumber'] = df_encoded['cylindernumber'].map(cylinder_map)
nominal_cols = ['carbody', 'drivewheel', 'enginetype', 'fuelsystem', 'carbrand']
df_encoded = pd.get_dummies(df_encoded, columns=nominal_cols, drop_first=True)
print(f"Shape after encoding: {df_encoded.shape}")
df_encoded.head()

X = df_encoded.drop(columns=['price'])
y = df_encoded['price']

print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.histplot(df['price'], kde=True, bins=30, ax=axes[0], color='steelblue')
axes[0].set_title('Distribution of Car Prices')
axes[0].set_xlabel('Price')

sns.boxplot(x=df['price'], ax=axes[1], color='lightcoral')
axes[1].set_title('Boxplot of Car Prices')
axes[1].set_xlabel('Price')

plt.tight_layout()
plt.show()

print(f"Price skewness: {df['price'].skew():.2f}")

plt.figure(figsize=(8, 5))
sns.regplot(x='horsepower', y='price', data=df, scatter_kws={'alpha': 0.6}, line_kws={'color': 'red'})
plt.title('Horsepower vs Price')
plt.xlabel('Horsepower')
plt.ylabel('Price')
plt.show()

print(f"Correlation (horsepower, price): {df['horsepower'].corr(df['price']):.3f}")

plt.figure(figsize=(8, 5))
sns.regplot(x='enginesize', y='price', data=df, scatter_kws={'alpha': 0.6}, line_kws={'color': 'red'})
plt.title('Engine Size vs Price')
plt.xlabel('Engine Size')
plt.ylabel('Price')
plt.show()

print(f"Correlation (enginesize, price): {df['enginesize'].corr(df['price']):.3f}")

plt.figure(figsize=(8, 5))
sns.regplot(x='curbweight', y='price', data=df, scatter_kws={'alpha': 0.6}, line_kws={'color': 'red'})
plt.title('Curb Weight vs Price')
plt.xlabel('Curb Weight')
plt.ylabel('Price')
plt.show()

print(f"Correlation (curbweight, price): {df['curbweight'].corr(df['price']):.3f}")

plt.figure(figsize=(12, 9))
corr_matrix = df[numcols].corr()
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', center=0,
            linewidths=0.5, cbar_kws={'label': 'Correlation'})
plt.title('Correlation Heatmap — Numerical Attributes')
plt.tight_layout()
plt.show()

price_corr = corr_matrix['price'].drop('price').sort_values(key=abs, ascending=False)
print("Features most strongly correlated with price:")
print(price_corr)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Training set: {X_train.shape[0]} records")
print(f"Testing set:  {X_test.shape[0]} records")

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

print("Model trained.")
print(f"Intercept: {lr_model.intercept_:.2f}")

y_pred = lr_model.predict(X_test)
pd.DataFrame({'Actual': y_test.values, 'Predicted': y_pred}).head(10)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Multiple Linear Regression — Test Set Performance")
print("-" * 50)
print(f"MAE  (Mean Absolute Error) : {mae:,.2f}")
print(f"MSE  (Mean Squared Error)  : {mse:,.2f}")
print(f"RMSE (Root Mean Sq. Error) : {rmse:,.2f}")
print(f"R2 Score                   : {r2:.4f}")

plt.figure(figsize=(8, 7))
plt.scatter(y_test, y_pred, alpha=0.7, color='teal', edgecolor='k')
lims = [min(y_test.min(), y_pred.min()), max(y_test.max(), y_pred.max())]
plt.plot(lims, lims, 'r--', label='Perfect Prediction (y = x)')
plt.xlabel('Actual Price')
plt.ylabel('Predicted Price')
plt.title('Actual Price vs Predicted Price')
plt.legend()
plt.tight_layout()
plt.show()

residuals = y_test - y_pred

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].scatter(y_pred, residuals, alpha=0.7, color='darkorange', edgecolor='k')
axes[0].axhline(y=0, color='red', linestyle='--')
axes[0].set_xlabel('Predicted Price')
axes[0].set_ylabel('Residual (Actual - Predicted)')
axes[0].set_title('Residual Plot')

sns.histplot(residuals, kde=True, ax=axes[1], color='mediumpurple')
axes[1].set_title('Distribution of Residuals')
axes[1].set_xlabel('Residual')

plt.tight_layout()
plt.show()

print(f"Mean residual: {residuals.mean():.2f} (should be close to 0)")

new_car = X_train.mean(numeric_only=True).to_frame().T
new_car = new_car.reindex(columns=X.columns, fill_value=0)
for col in new_car.columns:
    if col.startswith(('carbody_', 'drivewheel_', 'enginetype_', 'fuelsystem_', 'carbrand_')):
        new_car[col] = 0

new_car_specs = {
    'symboling': 0,
    'fueltype': 1,
    'aspiration': 0,
    'doornumber': 1,
    'enginelocation': 0,
    'wheelbase': 99.0,
    'carlength': 175.0,
    'carwidth': 66.0,
    'carheight': 54.0,
    'curbweight': 2500,
    'cylindernumber': 4,
    'enginesize': 140,
    'boreratio': 3.3,
    'stroke': 3.3,
    'compressionratio': 9.0,
    'horsepower': 110,
    'peakrpm': 5200,
    'citympg': 27,
    'highwaympg': 33,
}
for k, v in new_car_specs.items():
    if k in new_car.columns:
        new_car[k] = v
for flag in ['carbody_sedan', 'drivewheel_fwd', 'enginetype_ohc', 'fuelsystem_mpfi', 'carbrand_toyota']:
    if flag in new_car.columns:
        new_car[flag] = 1

predicted_price = lr_model.predict(new_car)[0]
print("New car specification:")
for k, v in new_car_specs.items():
    print(f"  {k}: {v}")
print(f"\nPredicted price: ${predicted_price:,.2f}")

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
lr_scaled = LinearRegression().fit(X_train_scaled, y_train)

ridge_model = Ridge(alpha=10.0, random_state=42).fit(X_train_scaled, y_train)
lasso_model = Lasso(alpha=10.0, random_state=42, max_iter=10000).fit(X_train_scaled, y_train)

models = {
    'Linear Regression': lr_scaled,
    'Ridge Regression': ridge_model,
    'Lasso Regression': lasso_model,
}

results = []
for name, model in models.items():
    preds = model.predict(X_test_scaled)
    results.append({
        'Model': name,
        'MAE': mean_absolute_error(y_test, preds),
        'MSE': mean_squared_error(y_test, preds),
        'RMSE': np.sqrt(mean_squared_error(y_test, preds)),
        'R2 Score': r2_score(y_test, preds),
    })

results_df = pd.DataFrame(results).set_index('Model')
results_df.round(3)

results_df[['MAE', 'RMSE']].plot(kind='bar', figsize=(8, 5), color=['steelblue', 'salmon'])
plt.title('Error Comparison: Linear vs Ridge vs Lasso')
plt.ylabel('Error')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

results_df[['R2 Score']].plot(kind='bar', figsize=(8, 5), color='seagreen', legend=False)
plt.title('R2 Score Comparison: Linear vs Ridge vs Lasso')
plt.ylabel('R2 Score')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

lasso_coefs = pd.Series(lasso_model.coef_, index=X.columns)
zeroed = lasso_coefs[lasso_coefs == 0]
kept = lasso_coefs[lasso_coefs != 0].sort_values(key=abs, ascending=False)

print(f"Lasso zeroed out {len(zeroed)} of {len(lasso_coefs)} features:")
print(list(zeroed.index))

print(f"\nTop features Lasso considers most important:")
kept.head(10)

